bug fix: scraping course
kartoza/feti pull request #280
Opened 2016-09-28 02:40 UTC by meomancer

2016-09-28 04:12 UTC, dimasciput commented
Got another error : 
```
Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python3.4/site-packages/django/core/management/__init__.py", line 354, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python3.4/site-packages/django/core/management/__init__.py", line 346, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/local/lib/python3.4/site-packages/django/core/management/base.py", line 394, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/usr/local/lib/python3.4/site-packages/django/core/management/base.py", line 445, in execute
    output = self.handle(*args, **options)
  File "/home/web/django_project/feti/management/commands/scraping_course.py", line 130, in handle
    create_course(course)
  File "/home/web/django_project/feti/management/commands/scraping_course.py", line 73, in create_course
    course.save()
  File "/home/web/django_project/feti/models/course.py", line 114, in save
    super(Course, self).save(*args, **kwargs)
  File "/usr/local/lib/python3.4/site-packages/django/db/models/base.py", line 685, in save
    "unsaved related object '%s'." % field.name
ValueError: save() prohibited to prevent data loss due to unsaved related object 'field_of_study'.
```

2016-09-28 05:16 UTC, dimasciput commented
```
 for obj in self.query.objs
  File "/usr/local/lib/python3.4/site-packages/django/db/models/sql/compiler.py", line 931, in <listcomp>
    for obj in self.query.objs
  File "/usr/local/lib/python3.4/site-packages/django/db/models/sql/compiler.py", line 929, in <listcomp>
    ) for f in fields
  File "/usr/local/lib/python3.4/site-packages/django/db/models/fields/__init__.py", line 710, in get_db_prep_save
    prepared=False)
  File "/usr/local/lib/python3.4/site-packages/django/db/models/fields/__init__.py", line 702, in get_db_prep_value
    value = self.get_prep_value(value)
  File "/usr/local/lib/python3.4/site-packages/django/db/models/fields/__init__.py", line 1869, in get_prep_value
    return int(value)
ValueError: invalid literal for int() with base 10: 'Field 51'
```

2016-09-29 03:31 UTC, dimasciput commented
@meomancer still got this error : 
```
psycopg2.DataError: value too long for type character varying(500)


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python3.4/site-packages/django/core/management/__init__.py", line 354, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python3.4/site-packages/django/core/management/__init__.py", line 346, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/local/lib/python3.4/site-packages/django/core/management/base.py", line 394, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/usr/local/lib/python3.4/site-packages/django/core/management/base.py", line 445, in execute
    output = self.handle(*args, **options)
  File "/home/web/django_project/feti/management/commands/scraping_occupation.py", line 202, in handle
    create_occupation(occupation)
  File "/home/web/django_project/feti/management/commands/scraping_occupation.py", line 59, in create_occupation
    occupation.save()
  File "/usr/local/lib/python3.4/site-packages/django/db/models/base.py", line 734, in save
    force_update=force_update, update_fields=update_fields)
  File "/usr/local/lib/python3.4/site-packages/django/db/models/base.py", line 762, in save_base
    updated = self._save_table(raw, cls, force_insert, force_update, using, update_fields)
  File "/usr/local/lib/python3.4/site-packages/django/db/models/base.py", line 846, in _save_table
    result = self._do_insert(cls._base_manager, using, fields, update_pk, raw)
  File "/usr/local/lib/python3.4/site-packages/django/db/models/base.py", line 885, in _do_insert
    using=using, raw=raw)
  File "/usr/local/lib/python3.4/site-packages/django/db/models/manager.py", line 127, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/usr/local/lib/python3.4/site-packages/django/db/models/query.py", line 920, in _insert
    return query.get_compiler(using=using).execute_sql(return_id)
  File "/usr/local/lib/python3.4/site-packages/django/db/models/sql/compiler.py", line 974, in execute_sql
    cursor.execute(sql, params)
  File "/usr/local/lib/python3.4/site-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
  File "/usr/local/lib/python3.4/site-packages/django/db/utils.py", line 98, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "/usr/local/lib/python3.4/site-packages/django/utils/six.py", line 685, in reraise
    raise value.with_traceback(tb)
  File "/usr/local/lib/python3.4/site-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
django.db.utils.DataError: value too long for type character varying(500)
```

2016-09-29 03:38 UTC, meomancer commented
@dimasciput have you migrated it?
https://github.com/kartoza/feti/pull/280/commits/f587c21bda0dfe20ada08a6f9673f73459e0eacc#diff-0826d3bd63c7f584ae129b20402ed211R20
it is already in textField

2016-09-29 06:22 UTC, dimasciput commented
@meomancer already migrated, found another issue: 

```
Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python3.4/site-packages/django/core/management/__init__.py", line 354, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python3.4/site-packages/django/core/management/__init__.py", line 346, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/local/lib/python3.4/site-packages/django/core/management/base.py", line 394, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/usr/local/lib/python3.4/site-packages/django/core/management/base.py", line 445, in execute
    output = self.handle(*args, **options)
  File "/home/web/django_project/feti/management/commands/scraping_occupation.py", line 134, in handle
    content = content.split("<b>Description</b>")[1]
IndexError: list index out of range
```

2016-09-29 06:23 UTC, dimasciput commented
I think it will be good if you create test case for this.

2016-09-30 08:39 UTC, dimasciput requested changes

2016-09-30 08:39 UTC, dimasciput commented on django_project/feti/tests/test_scraping.py
> +        call_command('scraping_campus', *args, **opts)
I think the tests could be better, we don't need to call the command management and waiting to download all data. For example you could create a dummy data and tests your parsing function.

2016-09-30 09:23 UTC, meomancer commented on django_project/feti/tests/test_scraping.py
> +        call_command('scraping_campus', *args, **opts)
ah, maybe i will just scrap 1 page instead make dummy data
because if i make dummy data, i will give just optimal data, that will pass

2016-09-30 09:54 UTC, dimasciput commented on django_project/feti/tests/test_scraping.py
> +        call_command('scraping_campus', *args, **opts)
Hmm you can create multiple dummy data that have different condition. I think it best if we keep the test as lightweight as possible, downloading data from another source will takes time.

2016-10-12 10:41 UTC, dimasciput commented
Updates :
 
- Get location data when scraping campus
- Scraping courses from ncap site, then get the detail information from saqa. Add courses to provider.

2016-10-12 10:41 UTC, dimasciput approved these changes

2016-10-12 10:41 UTC, merged