Update occupation page
kartoza/feti pull request #318
Opened 2016-11-21 10:31 UTC by dimasciput

Improve occupation page :

![feti](https://cloud.githubusercontent.com/assets/1979569/20479269/33273450-b010-11e6-84dc-d49f8dda139a.gif)

2016-11-23 02:11 UTC, dimasciput commented
@cchristelis can you review this? I also updated the tests

2016-11-27 18:52 UTC, cchristelis commented
@dimasciput, although this is nice work, we need to work through the SAQA ids. Why don't you just change the hyperlink that the Steps are pointing to to "/#map/course/saqa_id=X"?

2016-11-28 02:51 UTC, dimasciput commented
Hi @cchristelis , your comment is not showing up. Mind to repost it again? Thanks!

2016-11-28 08:01 UTC, cchristelis commented
@dimasciput, I have updated the comment.

2016-11-28 08:01 UTC, cchristelis requested changes

2016-11-28 08:01 UTC, cchristelis commented on django_project/feti/search_backends/fuzzy_elastic_backend.py
> +            try:
rather than a try and except, let's rather check whether the keyword is in the dict:
```
if "min_score" not in search_kwargs:
```

2016-11-28 09:24 UTC, merged