edited icons and add legend
kartoza/feti pull request #463
Opened 2017-04-04 09:52 UTC by ann26

fix #359 

![screenshot from 2017-04-04 16-51-49](https://cloud.githubusercontent.com/assets/26101337/24651176/0f1b0e78-1957-11e7-996f-7f631df6f882.png)

2017-04-04 10:28 UTC, dimasciput requested changes
Still a couple of things to fix, also is this only on 'Where to study' tab? What happens in 'What to study'?

2017-04-04 10:28 UTC, dimasciput commented on django_project/feti/api_views/campus.py
> +                del stored_fields['campus_public_institution']
We need this attribute, don't remove this.

2017-04-04 10:28 UTC, dimasciput commented on django_project/feti/static/js/scripts/views/map.js
> +            return div
Please fix the indentation

2017-04-04 12:02 UTC, ann26 commented
this also applies to 'what to study' tab
![screenshot from 2017-04-04 19-01-10](https://cloud.githubusercontent.com/assets/26101337/24655616/2554226c-1969-11e7-88a2-945137a01066.png)

2017-04-05 06:32 UTC, dimasciput commented
@ann26 so that's still a problem, you need to update the backend for the 'what to study' tab.

2017-04-05 08:53 UTC, ann26 commented
updated:
in 'what to study' we can now differentiate public and private

![screenshot from 2017-04-05 15-49-10](https://cloud.githubusercontent.com/assets/26101337/24697607/ffece202-1a17-11e7-9a5e-93c04bed46b1.png)

2017-04-06 01:35 UTC, dimasciput approved these changes

2017-04-06 06:19 UTC, dimasciput commented
LGTM

2017-04-06 06:26 UTC, merged