Extending API
kartoza/feti pull request #512
Opened 2017-10-22 23:36 UTC by sonlinux

Fix #503 
I have added most of the missing API views to the existing API, which include for models:

- url

- address

- course provider link

-  education training quality

- abet band

-  national graduate school in education

- national certificate vocation

- feedback

- qual class

- pre 2009 national qualifications framwork

2017-11-07 06:36 UTC, sonlinux commented
@cchristelis could you also review this PR again please, thanks. And comment so that I can merge the changes. Thanks.

2017-11-10 03:18 UTC, meomancer commented
hi @sonlinux 
i'm not sure the purpose of the API that just return all
my suggestion is maybe API can be filtered by some fields
or maybe you could change url using
```
api/national_graduate-school_in_education/all
```
because in my mind, API can be filtering, not just return all data, because it will not be usable

2017-11-10 03:24 UTC, meomancer commented on django_project/feti/api_views/address.py
> +        bands = Address.objects.all()
please rename variable accordingly

2017-11-10 03:25 UTC, anitanh requested changes

2017-11-10 03:25 UTC, ann26 commented on django_project/feti/api_views/abet_band.py
> +class AbetBandApiView(APIView):
hi @sonlinux what is this?

2017-11-10 03:27 UTC, ann26 commented on django_project/feti/api_views/address.py
> +class AddressApiView(APIView):
Returning only all addresses are meaningless, we don't know whose address is this

2017-11-10 03:30 UTC, ann26 commented on django_project/feti/api_views/feedback.py
> +class FeedbackApiView(APIView):
I am not sure if we need this. We can see all feedbacks in the admin view though.

2017-11-10 03:34 UTC, ann26 commented
I agree with @meomancer

2017-11-10 09:57 UTC, sonlinux commented on django_project/feti/api_views/address.py
> +        bands = Address.objects.all()
Alright thanks @meomancer let me do so.

2017-11-10 09:58 UTC, sonlinux commented
Thanks @meomancer and @ann26 let me make the necessary changes.

2017-12-26 03:47 UTC, dimasciput commented
@sonlinux any progress for this?

2018-01-24 08:20 UTC, closed without merging