[WIP] optimize page load times and api calls
kartoza/feti pull request #580
Opened 2018-07-23 09:44 UTC by myarjunar

fix #557

2018-07-23 11:00 UTC, cchristelis commented on deployment/docker/REQUIREMENTS.txt
> +#profiling
commented out code shouldn't be part of a commit...

2018-07-24 14:17 UTC, myarjunar commented
can we merge this @cchristelis  ?

2018-07-25 04:14 UTC, meomancer commented on django_project/core/settings/base.py
> +# Directory where the result of api profiling is being stored.
remove this commented lines

2018-07-25 04:16 UTC, meomancer commented on django_project/feti/serializers/step_detail_serializer.py
> +        if not courses:
instead of using `if not courses`, maybe use `if courses`?
because it return same which is res

2018-07-25 04:16 UTC, meomancer requested changes
please see my comment

2018-07-25 04:51 UTC, meomancer approved these changes

2018-07-25 04:51 UTC, myarjunar commented
@meomancer thanks for reviewing. it's updated. let me know if there is another thing I need to fix

2018-07-25 04:51 UTC, meomancer commented
LGTM

2018-07-25 04:52 UTC, merged